Mail pre meetup
Noders/Comunicaciones pull request #48
Opened 2018-04-27 17:32 UTC by cristofer-dev

- ADD Data meetup May
- ADD draft first mail

2018-04-27 17:51 UTC, Xabadu requested changes
Un puro detalle.

2018-04-27 17:51 UTC, Xabadu commented on data/2018-05.json
> +      "title": "Stan, monitoreando aplicaciones Nodejs en 20 minutos",
`Node.js`

2018-04-28 18:42 UTC, Xabadu requested changes
Uno más

2018-04-28 18:42 UTC, Xabadu commented on data/2018-05.json
> +  "name": "Noders: Infinnity var",
`Infinity`

2018-04-28 18:43 UTC, Xabadu commented on data/2018-05.json
> +  "name": "Noders: Infinnity var",
`Infinity`

2018-04-28 18:43 UTC, Xabadu requested changes
Uno más

2018-05-02 01:38 UTC, L0rdKras commented on emails/2018/05/pre-meetup.md
> +Recuerden que nos reuniremos este Miércoles 02 de Mayo a las 19:00 tenemos nuestro BurgerJS, una iniciativa simple, reunirnos en un local, comer hamburguesas, conocer gente nueva, compartir y convers
Esta como rara la redacción

Cambiaría `Recuerden que nos reuniremos...` por algo así como `Además`, o algo así.

2018-05-02 01:42 UTC, DMaster69 commented on emails/2018/05/pre-meetup.md
> +Recuerden que **hoy** Miércoles 02 de Mayo a las 19:00 tenemos nuestro BurgerJS, una iniciativa simple, reunirnos en un local, comer hamburguesas, conocer gente nueva, compartir y conversar. [Confirm
Cambiaría `tenemos nuestro...` Por `tenemos una nueva version de ...`

2018-05-02 02:00 UTC, rodrigoAdones approved these changes

2018-05-09 00:56 UTC, merged