ADD Mail PostMeetup
Noders/Comunicaciones pull request #6
Opened 2017-09-22 03:47 UTC by cristofer-dev

Changes to be committed:
	new file:   2017-09-22-post-meetup

2017-09-22 13:30 UTC, Xabadu requested changes
Algunos comentarios

2017-09-22 13:30 UTC, Xabadu commented on 2017-09-22-post-meetup
> +
Hay una línea en blanco sobrante que se puede eliminar acá.

2017-09-22 13:30 UTC, Xabadu commented on 2017-09-22-post-meetup
> +Gracias a todos por haber asistido y participado el último meetup.
*participado en

2017-09-22 13:30 UTC, Xabadu commented on 2017-09-22-post-meetup
> +¡Queremos agradecer de forma especial a nuestro amigos, sponsors de AxiomZen por prestarnos sus oficinas para evento!
Ese `amigos, sponsors` suena raro, creo q el sponsors se puede eliminar y dejar solamente el `nuestros amigos de AxiomZen` o 'queremos agradecer a AxiomZen`

2017-09-22 13:30 UTC, Xabadu commented on 2017-09-22-post-meetup
> +Queremos agradecer a los expositores por darse el tiempo de compartir su experiencia con nosotros:
Hay una redundancia de `Queremos agradecer` acá. Quizás cambiar el inicio de esta línea con un `Adicionalmente...`?

2017-09-22 13:30 UTC, Xabadu commented on 2017-09-22-post-meetup
> +Invitamos también a quienes quieran pertenecer a nuestro grupo de patrocinadores. Pueden colaborar con nosotros como venue (prestando espacios para los eventos), con las pizzas o las cervezas. ¡Todo
`escríbenos`

2017-09-22 13:30 UTC, Xabadu commented on 2017-09-22-post-meetup
> +Sabemos que tienes una charla fantástica que compartir y ¡queremos escucharte! Te invitamos a registrar tu charla (15 – 30 minutos) o lightning (5 – 10 minutos) con una issue en este link (https://gi
`un issue`

2017-09-22 14:59 UTC, L0rdKras commented
@cristofer-dev en la parte de los speakers falta el link a sus redes( usuario de twitter), o no se si ponerlo como link en sus nombres.
También falta recordar que se pongan en contactos con ellos si están buscando trabajo, ya que los tres dijeron que en sus empresas necesitan devs.

2017-09-22 15:01 UTC, cristofer-dev commented
si los linkeamos a sus perfiles de Github ?

2017-09-22 15:05 UTC, L0rdKras commented
Sí, de hecho es mejor

2017-09-25 14:00 UTC, fforres commented
Esperaría por info en estos 3, updeteamos y mergeamos :) 

https://github.com/Noders/Meetups/issues/52 
https://github.com/Noders/Meetups/issues/51
https://github.com/Noders/Meetups/issues/49

2017-09-26 13:44 UTC, closed without merging